name: Deploy to Production

on:
  push:
    branches:
      - master  # Agar sening branching `main` bo‘lsa, `master`ni `main`ga almashtirdim

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#Prod')  # Faqat commit mesajida #Prod bo‘lsa ishlaydi
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v2

      - name: 📤 Copy files to server using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "."
          target: "/home/test1/PythonProject/.github/workflows/deploy.yml"

      - name: 🚀 Deploy with Docker Compose via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/test1/PythonProject/.github/workflows/deploy.yml
            docker-compose down
            docker-compose up -d --build
