name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📂 Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 213.230.71.173         # 💡 PUBLIC IP ni shu yerga yozasan
        port: 5100                   # 💡 Shu portni berishgan — to‘g‘ri yoz
        username: root              # 💡 Kirayotgan login — root
        key: ${{ secrets.SSH_KEY }} # 💡 GitHub Secret’ga qo‘yilgan private key
        script: |
          cd /home/test1/PythonProject
          docker-compose down
          git pull origin main
          docker-compose up -d --build
