name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 213.230.71.173
          username: root
          port: 5100
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test1/PythonProject
            git pull origin main
            docker compose down || docker-compose down
            docker compose up -d --build || docker-compose up -d --build
