name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 5100 213.230.71.173 >> ~/.ssh/known_hosts

      - name: Deploy to remote server
        run: |
          ssh -p 5100 root@213.230.71.173 << 'EOF'
            cd /home/test1/PythonProject
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
