name: Flask Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/test1/PythonProject
          git pull origin main
          docker stop flask-site || true
          docker rm flask-site || true
          docker build -t flask-site .
          docker run -d -p 5000:5000 --name flask-site flask-site
